# Generated by Django 2.1.1 on 2018-10-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20181005_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemessage',
            name='link',
            field=models.CharField(max_length=1000000),
        ),
    ]
