# Generated by Django 2.1.1 on 2018-10-11 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0008_auto_20181011_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PictureMessage',
        ),
    ]
