# Generated by Django 2.1.1 on 2018-10-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0009_delete_picturemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
