# Generated by Django 2.1.1 on 2018-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0010_picturemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talker', models.CharField(max_length=10000)),
                ('message', models.CharField(max_length=10000)),
                ('time', models.CharField(max_length=10000)),
            ],
        ),
    ]
